"""The learning layer: turn the slap ledger into something a bot actually carries into its next round.

What existed before was a punishment, not a memory:

  * `slap.py` appended the rule's text to the offender's SOUL.md at level 2. Ten near-identical
    sentences accumulated (forge's SOUL.md reached 8 KB of them), while the *count* that made them
    meaningful - "you have done this 8 times" - was nowhere the bot could see it.
  * nothing re-read the ledger at round start, so a bot began every round with the same amnesia.
  * `status: CLEAN` closed the artefact, not the behaviour; the same class returned an hour later.

This module is the read side of the ledger:

  docs/LESSONS.md        machine-generated truth: per bot, per class, count, level, what enforces it now
  SOUL.md block          a bounded, deduplicated, per-class block replacing the pile of sentences
  history_line(bot)      the one paragraph injected into every build brief, so the round STARTS knowing

Everything here is derived from docs/slaps.json - never hand-written, so it cannot drift from history.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from tools.studio import rules

ROOT = Path(__file__).resolve().parents[2]
LEDGER_JSON = ROOT / "docs" / "slaps.json"
LESSONS_MD = ROOT / "docs" / "LESSONS.md"
BACKUP = ROOT / "runs" / "studio" / "soul_backup"

HEADER = "## Correction rules (written by WARDEN — non-negotiable)"
SOUL_HEADER_ALT = "## Correction rules (written by WARDEN"
SOUL_FOR = {
    "forge": Path(r"C:\Users\dbshe\AppData\Local\hermes\profiles\forge\SOUL.md"),
    "chip": Path(r"C:\Users\dbshe\AppData\Local\hermes\profiles\chip\SOUL.md"),
    "pixel": Path(r"C:\Users\dbshe\AppData\Local\hermes\profiles\pixel\SOUL.md"),
    "lore": Path(r"C:\Users\dbshe\AppData\Local\hermes\profiles\lore\SOUL.md"),
    "lens": Path(r"C:\Users\dbshe\AppData\Local\hermes\profiles\lens\SOUL.md"),
    "warden": Path(r"C:\Users\dbshe\AppData\Local\hermes\profiles\warden\SOUL.md"),
}
MAX_CLASSES = 8          # a bot cannot act on 20 rules; the top classes are the ones that recur
MAX_CHARS = 2600         # hard cap on the generated block - SOUL.md must not grow without bound


def load_ledger() -> dict:
    if not LEDGER_JSON.is_file():
        return {"version": 1, "slaps": []}
    try:
        return json.loads(LEDGER_JSON.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return {"version": 1, "slaps": []}


def class_rows(ledger: dict, bot: str) -> list[dict]:
    """This bot's offence classes, worst first (count desc, then level desc)."""
    st = rules.stats(ledger).get(bot, {})
    rows = sorted(st.values(), key=lambda r: (-r["count"], -r["level"], r["rule_id"]))
    return rows


def history_line(bot: str, ledger: dict | None = None) -> str:
    """The paragraph injected into the bot's round brief - its own record, in its own face.

    Stated as history and a pre-flight check, not as a scolding: the point is that the class of
    mistake is named before the work starts, when it is still cheap to avoid.
    """
    ledger = ledger or load_ledger()
    rows = class_rows(ledger, bot)
    if not rows:
        return "YOUR OWN HISTORY: no open offences on record. Keep it that way."
    total = sum(r["count"] for r in rows)
    out = ["YOUR OWN HISTORY (%d slap(s) on record - every one of these can be checked "
           "mechanically, so do it before you report done):" % total]
    for r in rows[:MAX_CLASSES]:
        meta = rules.rule_of(r["rule_id"])
        flag = {1: "warned", 2: "rule in your SOUL.md", 3: "LANE FROZEN"}[r["level"]]
        out.append("- %s x%d [%s] %s" % (r["rule_id"], r["count"], flag, meta["title"]))
        if meta.get("check"):
            out.append("    before you finish: %s" % meta["check"])
    if rows[0]["level"] >= 3:
        out.append("Your worst class is at level 3 (frozen lane). Clear it first, or say BLOCKED.")
    return "\n".join(out)


def render_lessons(ledger: dict) -> str:
    """docs/LESSONS.md - the whole picture, generated. The number that matters is `times`, the same
    class recurring after it was closed CLEAN is what proves a fix verified the artefact, not the bot."""
    st = rules.stats(ledger)
    total = len(ledger.get("slaps", []))
    closed = sum(1 for s in ledger.get("slaps", [])
                 if str(s.get("status", "")).startswith("CLEAN"))
    lines = [
        "# LESSONS — what the studio has learned (generated, do not hand-edit)",
        "",
        "Generated by `python -m tools.studio.learn --all` from `docs/slaps.json`.",
        "",
        "`%d` slaps recorded; `%d` closed as CLEAN. A CLEAN close means the artefact was fixed. The table"
        % (total, closed),
        "below is the other half of the truth: how many times the same *class* came back anyway.",
        "",
    ]
    for bot in sorted(st):
        total_bot = sum(r["count"] for r in st[bot].values())
        lines += ["## %s — %d slap(s), %d class(es)" % (bot, total_bot, len(st[bot])), "",
                  "| class | times | level | last | open | enforced by | rule |",
                  "|---|---|---|---|---|---|---|"]
        for r in sorted(st[bot].values(), key=lambda r: -r["count"]):
            meta = rules.rule_of(r["rule_id"])
            lines.append("| `%s` | %d | %d | %s | %d | %s | %s |"
                         % (r["rule_id"], r["count"], r["level"], r["last"], r["open"],
                            meta["enforced"], meta["rule"]))
        lines.append("")
    lines += ["## What is mechanically enforced now", ""]
    for meta in rules.RULES:
        if meta["enforced"].startswith("preflight:"):
            lines += ["- **%s** (%s) — %s" % (meta["id"], meta["enforced"], meta["check"] or meta["rule"])]
    lines += ["",
              "Classes with `enforced: review` still need a reviewer's judgement: they are the ones a",
              "checklist cannot close, so they must not be left to memory either.", ""]
    return "\n".join(lines)


def _replace_block(text: str, block: str) -> str:
    """Swap the generated correction block, preserving everything a human wrote around it."""
    idx = text.find(SOUL_HEADER_ALT)
    if idx < 0:
        return text.rstrip() + "\n\n\n" + block
    tail = text[idx:]
    nxt = tail.find("\n## ", 1)          # next real section after ours
    head = text[:idx].rstrip()
    rest = tail[nxt:].lstrip("\n") if nxt > 0 else ""
    return "%s\n\n\n%s\n%s" % (head, block, ("\n" + rest if rest else ""))


def sync_soul(bot: str, ledger: dict | None = None) -> str:
    """Rewrite this bot's correction block from the ledger: deduped by class, counted, capped."""
    ledger = ledger or load_ledger()
    path = SOUL_FOR.get(bot)
    if not path or not path.is_file():
        return "no SOUL.md found for %s" % bot
    text = path.read_text(encoding="utf-8")
    BACKUP.mkdir(parents=True, exist_ok=True)
    bak = BACKUP / ("%s-SOUL.md.bak" % bot)
    if not bak.is_file():
        bak.write_text(text, encoding="utf-8")

    rows = class_rows(ledger, bot)
    total = sum(r["count"] for r in rows)
    block = [HEADER, "",
             "<!-- generated by tools/studio/learn.py from docs/slaps.json - do not hand-edit -->",
             "",
             "You carry **%d** recorded offence(s) across **%d** class(es). Each one below can be checked"
             % (total, len(rows)),
             "by a command before you report a round done. Class counts are permanent: rewording a rule",
             "does not reset them, and a CLEAN fix closes the artefact, not the count.", ""]
    for r in rows[:MAX_CLASSES]:
        meta = rules.rule_of(r["rule_id"])
        flag = {1: "warned", 2: "escalated", 3: "FROZEN until an acceptance command verifies"}[r["level"]]
        block.append("- **%s ×%d — %s** (%s). %s" % (meta["id"], r["count"], meta["title"], flag,
                                                     meta["rule"]))
        if meta.get("check"):
            block.append("  - *check before done:* %s" % meta["check"])
    if len(rows) > MAX_CLASSES:
        block.append("- ...and %d more class(es); see docs/LESSONS.md." % (len(rows) - MAX_CLASSES))
    if total == 0:
        block.append("- nothing on record.")
    out = "\n".join(block).strip() + "\n"
    if len(out) > MAX_CHARS:                       # never blow up the file that loads every session
        out = out[:MAX_CHARS].rsplit("\n- ", 1)[0] + "\n"
    new = _replace_block(text, out)
    if new != text:
        path.write_text(new, encoding="utf-8")
    return "%s: %d class(es) / %d slap(s) -> SOUL.md %d -> %d bytes" % (
        bot, min(len(rows), MAX_CLASSES), total, len(text), len(new))


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog="python -m tools.studio.learn")
    ap.add_argument("--all", action="store_true", help="write docs/LESSONS.md and sync every bot's SOUL.md")
    ap.add_argument("--lessons", action="store_true", help="write docs/LESSONS.md only")
    ap.add_argument("--history", metavar="BOT", help="print the brief paragraph for one bot")
    ap.add_argument("--sync", metavar="BOT", help="sync one bot's SOUL.md block")
    args = ap.parse_args(argv)
    ledger = load_ledger()

    if args.history:
        print(history_line(args.history, ledger))
        return 0
    if args.sync:
        print(sync_soul(args.sync, ledger))
        return 0
    if args.all or args.lessons:
        LESSONS_MD.write_text(render_lessons(ledger), encoding="utf-8")
        print("wrote %s (%d bytes)" % (LESSONS_MD.relative_to(ROOT).as_posix(), LESSONS_MD.stat().st_size))
    if args.all:
        for bot in SOUL_FOR:
            print("  %s" % sync_soul(bot, ledger))
    if not any([args.all, args.lessons]):
        print(rules.summarise(ledger))
    return 0


if __name__ == "__main__":
    sys.exit(main())
